# Generated by Django 5.2.8 on 2025-11-08 16:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_passwordresettoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('access_admin_portal', 'Pode acessar o portal administrativo do site')],
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='cpf',
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=models.CharField(blank=True, help_text='Somente 11 dígitos (sem pontos/traços).', max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Informe 11 dígitos numéricos para o CPF.', regex='^\\d{11}$')], verbose_name='CPF'),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, verbose_name='Localizador')),
                ('origem', models.CharField(max_length=64)),
                ('destino', models.CharField(max_length=64)),
                ('partida', models.DateTimeField(verbose_name='Data/hora de partida')),
                ('chegada', models.DateTimeField(blank=True, null=True, verbose_name='Data/hora de chegada')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PAGO', 'Pago'), ('CANCELADO', 'Cancelado'), ('PENDENTE', 'Pendente')], default='PAGO', max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-partida', '-id'],
                'indexes': [models.Index(fields=['user', 'partida'], name='core_ticket_user_id_90778b_idx'), models.Index(fields=['codigo'], name='core_ticket_codigo_7e57f7_idx')],
            },
        ),
    ]
