# Generated by Django 5.2.8 on 2025-11-29 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_ticket_assentos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, verbose_name='Número do Voo/Localizador')),
                ('origem', models.CharField(max_length=64)),
                ('destino', models.CharField(max_length=64)),
                ('partida', models.DateTimeField(verbose_name='Data/hora de partida')),
                ('chegada', models.DateTimeField(blank=True, null=True, verbose_name='Data/hora de chegada')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço (R$)')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Voo (Oferta)',
                'verbose_name_plural': 'Voos (Ofertas)',
                'ordering': ['-partida'],
            },
        ),
    ]
