# Generated by Django 5.2.8 on 2025-11-30 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_ticket_assentos'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssentoOcupado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, verbose_name='Localizador / Código do voo')),
                ('assento', models.CharField(max_length=5)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['codigo'], name='core_assent_codigo_6b7995_idx')],
                'unique_together': {('codigo', 'assento')},
            },
        ),
    ]
